version: "3.9"
services:
  wavsep:
    # image: owaspvwad/wavsep
    build: ./wavsep
    ports:
      - 18080:8080
  wavsep-db:
    image: nsunina/wavsep-db:v1.5
    platform: linux/amd64
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
    wordpress_data: {}

        # mitmproxy:
        #   tty: true        
        #   image: mitmproxy/mitmproxy
        #   # command: mitmweb --web-iface 0.0.0.0
        #   command: mitmweb 
        #   ports: 
        #     - 8080:8080
